---
- name: Create empty file
  hosts: iaas
  become: yes
  tasks:
    - import_role:
        name: create_empty_file

- name: Fetch data about distro
  hosts: all
  become: yes
  tasks:
    - import_role:
        name: fetch_linux_distro
