---
# tasks file for create_empty_file
- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: { { destination_file } }
    state: touch
    mode: { { perm_mode } }
