---
- name: Create empty file
  hosts: iaas
  become: yes

  roles:
    - create_empty_file

- name: Fetch data about distro
  hosts: all
  become: yes

  roles:
    - fetch_linux_distro
  ansible.builtin.debug:
    var: result
  ansible.builtin.debug:
    msg: System has the following hostname {{ inventory_hostname }}